#!/bin/bash

socat -ddd -ddd PTY,link=$HOME/ipstack/slipdev,raw,echo=0 "EXEC:$HOME/ipstack/demo ,pty,raw,echo=0" &

sudo slattach -dv -p slip $HOME/ipstack/slipdev &

sudo ifconfig sl0 192.168.0.1 pointopoint 192.168.0.199 up

